@echo off
echo Deteniendo el servidor actual...
taskkill /F /IM node.exe
echo Esperando 2 segundos...
timeout /t 2 /nobreak
echo Iniciando el servidor con los cambios...
start node server.js
echo Servidor reiniciado correctamente.
